name:                learn-haskell
version:             0.0.0.0
github:              "boshen/learn-haskell"
license:             BSD3
author:              "Boshen"
maintainer:          "example@example.com"
copyright:           "2018 Boshen"

dependencies:
- base >= 4.7 && < 5
- hspec
- random
- QuickCheck

tests:
  learn-haskell-test:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
