name:                learn-haskell
version:             0.0.0.0
github:              "boshen/learn-haskell"
license:             BSD3
author:              "Boshen"
maintainer:          "example@example.com"
copyright:           "2018 Boshen"

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- comonad
- hspec
- random
- mtl
- containers
- parallel
- monad-par

tests:
  learn-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
